data:
  path: './assets_data/all_time'
  symbol: 'SP500'
  timeframe: '1d'
  start: '2000-01-01'
  end:   '2020-12-31'

strategy:
  module: 'ewmac'
  function: 'ewmac'

optimization:
  bundles: 10
  target: 'sharpe'
  param_grid:
    _module:     ['ewmac']
    _function:   ['ewmac']
    span_short:  [10, 16, 20]     # test three short‐span values
    span_long:   [50, 64, 80]     # three long‐span values
    vol_window:  [32]
    forecast_scale: [4.1]
    cap:         [20]
    weight:      [1.0]
    tau:         [0.2]
    capital:     [100000]
    idm:         [1.0]
    multiplier:  [5.0]
    fx:          [1.0]

output:
  root: './backtests'
  save_equity_curve: true
  save_drawdown_chart: true

fees:
  mapping: '/Users/aleylien/Desktop/backtester/fees and slippage/fees.json'
