# data / universe definitions
data:
  path: './assets_data/all_time'
  timeframe: '1d'
  start: '2000-01-01'
  end:   '2020-12-31'
  price_type: raw          # raw | normalized | normalised | norm
  normalized_price:
    method: ewm        # rolling | ewm
    window: 25             # for rolling
    span: 25               # for ewm; if omitted, falls back to 'window'
    min_periods: 10        # optional; default = max(5, window//3)
    scale: 100.0           # the “100 × …” factor in Carver
    start_value: 0.0       # P^N start level (0 per Carver)


# global optimization defaults (can be overridden per-strategy below)
optimization:
  bundles: 10
  target:  pnl  # sharpe, pnl, profit_factor, max_drawdown
  param_grid:
    _module:       ['ewmac']
    _function:     ['ewmac']
    span_short:    [10, 16, 20]
    span_long:     [50, 64, 80]
    vol_window:    [32]
    forecast_scale: [4.1]
    cap:           [20]
    tau:           [0.2]
    idm:           [1.0]
    multiplier:    [5.0]
    fx:            [1.0]

# where to write backtests, charts, etc.
output:
  root:               './backtests'
  save_equity_curve:   true
  save_drawdown_chart: true
  save_per_asset:      1
  save_per_instrument: true
  save_per_strategy: true
  plots.per_strategy: true

statistics:
  period_resolution: monthly   # monthly | quarterly

idm:
  enabled: true                # false -> use the scalar already in yaml
  mode: static                 # static | rolling
  floor_negatives: true        # ρ_ij <- max(ρ_ij, 0)
  min_overlap: 60              # minimum overlapping bars to compute ρ
  window: 250                  # for rolling IDM (e.g., ~1Y daily)
  returns_freq: daily          # daily | weekly
  fallback: 1.0                # used when not enough overlap

capital_policy:
  mode: reinvesting                 # none | reinvesting | periodic_rebalance
  reinvesting_frequency: monthly   # weekly | monthly | quarterly (3M)
  rebalance_frequency: quarterly   # monthly | quarterly

strategy_defaults:             # both params can be overwritten per strategy
  use_buffer: true
  buffer_F: 0.10

# fee schedule
fees:
  mapping: './config/fees.json'
fx:
  base_currency: 'USD'
  pairs_csv_dir: 'assets_data/fx'
  symbol_currency_map_file: 'config/symbol_currency_map.json'
market_meta:
  multipliers_file: 'config/multipliers.json'

# ──────────────────────────────────────────────────────────────────────────────
portfolio:
  # single total capital for the whole run
  capital: 100000
  tau: [0.2]
  #  max_open_trades: 4 uncomment if find-signal mode needed

  assets:
    - SP500
    - NASDAQ

  strategies:
    ewmac:
      module:   'ewmac'
      function: 'ewmac'
      param_grid:
        span_short:    [10, 16, 20]
        span_long:     [50, 64, 80]
        vol_window:    [32]
        cap:           [20]
        idm:           [1.0]
    trend_breakout:
      module: 'trend_breakout'
      function: 'trend_breakout'
      param_grid:
        horizon: [20, 25, 40, 50, 75, 80]
        cap: [ 20 ]
        vol_window: [ 32 ]

  assignments:
    default: [ewmac, trend_breakout]

    # you can override per-ticker, e.g.:
    # SP500: [ewmac, momentum]